cache:
  timeout: 500
  directories:
  - trinitycore
services: docker
language: cpp
compiler:
- clang
before_install:
- git clone -b 3.3.5 --single-branch https://github.com/TrinityCore/TrinityCore
install:
- "./scripts/build_3.3.5.sh"
script:
- "./scripts/publish_3.3.5.sh"
deploy:
  provider: releases
  api_key:
    secure: oCjiiDtjoDKwCKYUWF9mYXi74q6+daPl8sDmOWgkk6eRmcJNUjc99WttAvCXi3NMLIkZcHXSONs9Q0J2j6pzNusdJ7pbNDxVltoEorbodzC/107F621GmusEatlM4ik5gQaSbWoeON1vLYh+S76qlzmk6DlOma+SaIncElMdNe8dJSnSVoFs0hTjkx9eZ4AFZ7QEr8NAndw+O2eKuxSEL5HikGinf5/Z7hBBspiHdvQS/gLZv9cuXeuJHQY8GTf8hpOKBMuXT4L0eXNUBSp3TO6zTwHMKMNEza2KlN1I39ZNny/QcAC6L2romioSAPWH+Figc1KSkUxUqKPhOAm8hUeDvZzHmJhqgmzgR5JT1mdm+vSfOkW/hbvNogs5mXSVz5ZIxKiU7DZbx2LIRs1dR1Xj63Fgrr5NDu9VsRDz4x9efb4pkbEV64PMiJlQeKFABO2J7Bg6iirLNXWwv5Mj0S9+cAiSfpdgGCuFnLoSX1DKFHFhYs0bhyOjVoIQm/ieaoJ8riu9r7Q7r8LOM4OADkX+CbiYnlHW88SFU1O2iOJuuv8djXFQC6D0XI6R5HS9OSaqF4FNPjWBQ/3psFI8RTtno58q7lpRbZzKjBnFr1wSMMJP3wpavrMY6whYTJF/7HLQtSvPF5cUNnjRFNPkneXkQjOD3yi5AAqme6VLiXY=
  on:
    repo: dgonzalezruiz/trinitycore-builds
    tags: true
    all_branches: true
  file_glob: true
  skip_cleanup: true
  file: trinitycore-*.tar.gz
env:
  global:
  - secure: t/mSPZXb7Cpmse3BtJCoRlYoMCn/CnTalwVgMs0vM5tbh8Qtfzh7MjN6RN6mh8HxLm2sX+//BNrit+mMK+eSWZT6PdOtBk8Ib6A8c80MFfgYONhPccpqPpFjctAU8tEHBva5P1Pgx8xYPYmSyLJdZIUfZgt1Dkw/Yz5Lx8xKP6OrtIG4477yvaNTGaWLF9E06ei5rsOD25W354A92k0m2L9zJWhtEOn7fdwsgbzJ/JZZvmd3PsBmSx7oEJPRdel9vhXGcP9X36yTtai3BCdZFp0/Zl71Hpc2QYYdkZ4Otey282yuzTi+fKLPTpIRhxQhUDn4UCWe81abnh9u4LtgtPcpgRv0W+2QlZGPr/5O2u/5uYsHRGM3EthDHYVQlFJxu+19MVg//PZeHpHyncb8GbyMTpRVyLr2Pl0Oqs8olNB72CD+rsFTf9oSzHzCGqa2TEBiiS7AEbcZwhLUnWFeKmkPpMVP8DcmdqxrrjEjjPL/Sy4v9c/m2P4Wx1KQkfzEOZ0bJrFGR3HYJR43oGQgTZIORB1ClBFz/gqeTI6xhLrWMJ88q1VOzD7GKz89WxgnNmRlVdRb9KD+0YMXm0FkCv0QL/hpDDcQF3dLsYAY+lnJ/BNHMGb8LuvAuyhbV1LPYKfsoVadr347Nxmt7pA954f+Ki6eGsSYQ+xq6kNk6ww=
