
cache: 
  timeout: 7200
  directories:
    - trinitycore

services: docker
language: cpp
compiler:
  - clang

before_install:
  - "git clone -b 3.3.5 --single-branch https://github.com/TrinityCore/TrinityCore"
install:
  - "./scripts/build_3.3.5.sh"

script:
  - "./scripts/publish_3.3.5.sh"

deploy:
  provider: releases
  api_key:
    secure: oCjiiDtjoDKwCKYUWF9mYXi74q6+daPl8sDmOWgkk6eRmcJNUjc99WttAvCXi3NMLIkZcHXSONs9Q0J2j6pzNusdJ7pbNDxVltoEorbodzC/107F621GmusEatlM4ik5gQaSbWoeON1vLYh+S76qlzmk6DlOma+SaIncElMdNe8dJSnSVoFs0hTjkx9eZ4AFZ7QEr8NAndw+O2eKuxSEL5HikGinf5/Z7hBBspiHdvQS/gLZv9cuXeuJHQY8GTf8hpOKBMuXT4L0eXNUBSp3TO6zTwHMKMNEza2KlN1I39ZNny/QcAC6L2romioSAPWH+Figc1KSkUxUqKPhOAm8hUeDvZzHmJhqgmzgR5JT1mdm+vSfOkW/hbvNogs5mXSVz5ZIxKiU7DZbx2LIRs1dR1Xj63Fgrr5NDu9VsRDz4x9efb4pkbEV64PMiJlQeKFABO2J7Bg6iirLNXWwv5Mj0S9+cAiSfpdgGCuFnLoSX1DKFHFhYs0bhyOjVoIQm/ieaoJ8riu9r7Q7r8LOM4OADkX+CbiYnlHW88SFU1O2iOJuuv8djXFQC6D0XI6R5HS9OSaqF4FNPjWBQ/3psFI8RTtno58q7lpRbZzKjBnFr1wSMMJP3wpavrMY6whYTJF/7HLQtSvPF5cUNnjRFNPkneXkQjOD3yi5AAqme6VLiXY=
  on:
    repo: dgonzalezruiz/trinitycore-builds
    tags: true
    all_branches: true
  file_glob: true
  skip_cleanup: true
  file: trinitycore-*.tar.gz

env:
  global:
  - secure: tpteZ/fQ2OJQaOgyfAtL01ZJJXrwcc+KkWw8xrmFEsSKaf9vQyGbOs5Jz9z5Y6OSnKZhSk4knpabgF3WeBsL+mBJY0gm0rCymzjGLiPNxBlebc2Z8Tg2JlZFtvNiQCz/DY02mjHC410Qcf6Uoqg925UmqGWfSj9ApKBYPM3q5uEUz5TPRxrscntmFOm2PbdAY6zBN/2FVMNyQE7Sa13mTzKjDSORUxM3Pct11YBjla3FCN6aTtE8Z1QgCqGqqWBehJbLxY7BSbodMhWMudWrHw/hFu6XS8VeQu6ueM2rPn/q+GGOoyxpBtWo14IXDPT9MBrhJWvPGK22wGVuG5nb/jMmEW9qtdeew7BUaPOQTRPdsci4IbyCC8wQAeT6vQJY038DhLdcgnASRF9rCiEnQL32fC6HWmCgV5jdQle9As75Q3TXb69f8B8uIz94ZyS2ECEZOg259t3P0qyTiq0OkWLxyakIrUnttK2GwuqaeXJLEjmXGGKTfb1PoCkJp9Oew0938xPu5nf6gxaC3sQ572zF9zS5pzn7JWFw/38W7C2GqE9d8t1HChRaxc/+yL0irqyVthuRjjsxL+6EYllAMWZSbrEoIsLlMORhJAMa0myZg3ohmQ+fS/q+OeNzrmWDhvqE/VDuyCrC5pzfvJ/MBhIXc57Skey3WL73JcpHvNg=
