cache:
  timeout: 7200
  directories:
  - trinitycore
services: docker
language: cpp
compiler:
- clang
before_install:
- git clone -b 3.3.5 --single-branch https://github.com/TrinityCore/TrinityCore
- "./scripts/manage_cache.sh"
install:
- "./scripts/build_3.3.5.sh"
script:
- "./scripts/publish_3.3.5.sh"
deploy:
  provider: releases
  api_key:
    secure: lWXzGsT2IIU/EHiiIqadXBIfXF6Y/Ele6yaF4CeN0ey8sXm9M27hEd6HGdpemoK2RhNwWbbQHJpfpz2QI5FkFpfIHPLCcJUR3yBTCt8KhHq/A46QRwm+HwhkVjLDO2XyWDlbS4odiMxuCkj2l65pvKzA0vYIXpeSZTmEdw0uje/XCYfLklu298KafRDEAxEwDJCymYRe9WlqMTSyndb452tDi+9+W28GhsJ2/WZMzVCHwxXOQH0K8iDoE41CJxlg5mlRnntb+HO6CaUkQSoBLvijrGn2Z4/Kh0CjhsXEWK86ok9vp9QBl+VIl3tEhABAqfjieA8k4ki9rL2qa/PiDvopuv+nwsbt9lEQYQAKQJyzRbn/sHJwxI95io9IXSSdRepdP8nJAxetAOmwWgzTFm+JZ2sGKvULTkHs+6q5GLEzcYNKeiGDQrOeYvDZQ5mhOShB+9zDfNc0tP4VgxO4t7loFqHY5H3bgBWrqxOlgueUqhjpecp22oDYevrKpqyfJ5cLQazpvaxKQV/YWeUS1iNzshVafXUikwM1KK6g+8d7b003kJIhiyJ35rrCELeyglCzyaPgakyab9WXZrWUJOEktmwm0cyKWTGbewC0ovtQNWBha3Cq+4GXcCqwhqdT70pg1150r2CATz8P7pUIQxIaToJeH+tdzNakDWAaCeU=
  on:
    repo: dgonzalezruiz/trinitycore-builds
    tags: true
    all_branches: true
  file_glob: true
  skip_cleanup: true
  file: trinitycore-*.tar.gz
after_deploy:
- "./scripts/push_nami.sh"
env:
  global:
  - secure: C5y4X2ITb/LggnXhYyFasFkBRBSdOTqjl7BknXwdMdkAse5RPVo3dvyXQElsSzcvbLR9383zjIy0R28mB8VQYtqRt+brnZZplkldajkgtC0Vz9PcWbZ+nA/fVnC+HUZE2A+mZUK1yv6iJdyp6jxS6210TPjcwWjaaboq9OP3IIFYvLBCb8/W4wy45P+VQnnHg/3qtpdVv5emIkKOyqpmNpKd3IZl66FBOrqbcZFU7Hnzwr81LTtEvhaZG1BHfC6M08U6urZRLckIXq8WK21iq9Mc2svYWAcKqonVxRGeE7nf8ekfJEEtN/YYBv4UOefKKZrOSOyxViHNz8iULvOK+yClyBymNPjjc0XopzajhhOxG3fq+eftn6kASkRGrhXP6MCHwSH7IhCzO0YERXMVmzGm41DbAyjQbi0QAjaOXfbWvqMh3ANIeGkjSrMX/LF2TvuY2PCxRHx3OhzESuOTvfWpgvNlKT7ykSSA+pnWblmd2bcz0j6lw9lsX7jZ23xOVaqmP/3Qd5AzxGxIO/kTzPupuhN0xZt8RL/MIMIROcZMPWQzKlt3cKIyTmY1mmjrZ2cAPfURoi4C7m3RTeHnrRzVJWlmGY5ya0COt89rphYmQRjqgKpLDaUmeRkRTcOrl6q7ZBvCUpwHMDZ9S0bau38T/FOveix5MtulSKHM9vc=
